FROM docker.io/eclipse-temurin:17.0.1_12-jre
WORKDIR /application
EXPOSE 8080
COPY *.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
